on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]

# 开启执行权限
permissions:
  actions: write
  checks:  write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
        
# 运行job
jobs:
 build-and-test:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: install cpp
    run: sudo apt install -y libcppunit-dev
  - name: configure
  # 加上权限，否则不能运行
    run: chmod +x ./configure
  - name: make
    run: make
  - name: make makefile
    run: |

      echo "编译开始"
      make makefile
      echo "载入数据"
      mkdir gen
      cd gen
      touch hello.c
      echo github_user_name: ${{ github.repository_owner }}
      echo gif_out_path: ./github_user_name/gen/hello.o 


  - name: Execute
    run: |
        ./hello
  - name: Make file  commit
    run: |
        echo $(date) >> tick.txt
        git config --global user.email "2563043733@qq.com"
        git config --global user.name "ilikui"
        git add tick.txt
        git commit -m "Commit file  schedule counts"
        git status    
  - name: Push All
    run: |
        git diff 
        git add .
        git config --global user.email "2563043733@qq.com"
        git config --global user.name "ilikui"
        git commit -m "commit "
        git push

   
