on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]

# 开启执行权限
permissions:
  actions: write
  checks:  write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
        
# 运行job
jobs:
 build-and-test:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: install cppunit
    run: sudo apt install -y libcppunit-dev
  - name: configure
  # 加上权限，否则不能运行
    run: chmod +x ./configure
  - name: make
    run: make
  - name: make test
    run: make test